// ======================================
// Configuration สำหรับ Pre-Registration
// Generated by Config Builder
// ======================================

const CONFIG = {
    // ภาษา: 'th', 'en', 'id', 'ph', 'vn', 'zh'
    language: 'en',

    // Prefix สำหรับ id และ class (ถ้าไม่ต้องการ prefix ให้ใส่ '')
    prefix: 'prereg-',

    // URL ของ API
    apiUrl: 'https://secure2.playpark.com/PreRegisterAPI/PreRegisterAPI.ashx',

    // Event ID ที่ต้องการใช้งาน
    eventId: '37',

    // IP Detection API (สำหรับตรวจจับประเทศอัตโนมัติ)
    ipDetectionAPI: {
        enabled: true,
        url: 'https://ip2location.playpark.com/IP2locationAll.ashx'
    },

    // กำหนดฟิลด์ที่ใช้ในฟอร์ม
    fields: {
        // freeText1
        freeText1: {
            type: 'email',
            labelKey: 'email',
            placeholderKey: 'emailPlaceholder',
            required: true,
            htmlId: 'email',
            errorId: 'emailError',
            defaultValue: ''
        },

        // freeText2
        freeText2: {
            type: 'tel',
            labelKey: 'phone',
            placeholderKey: 'phonePlaceholder',
            required: false,
            htmlId: 'phone',
            errorId: 'phoneError',
            defaultValue: '',
            // ⭐ International Telephone Input Options
            useInternationalPhone: true,
            intlPhoneOptions: {
                initialCountry: '', // ตรวจจับอัตโนมัติจาก IP
                preferredCountries: ['th', 'sg', 'my', 'id', 'ph', 'vn']
            },
            // Auto-fill จาก IP Detection (th, sg, my, id, ph, vn; default sg)
            autoFillFrom: 'countryCode',
            allowedCountries: ['TH', 'SG', 'MY', 'ID', 'PH', 'VN'],
            fallbackDefault: 'SG'
        },

        // freeText3 - Auto-fill จาก IP Detection (th, sg, my, id, ph, vn; default sg)
        freeText3: {
            type: 'hidden',
            value: '',
            autoFillFrom: 'countryCode',
            allowedCountries: ['TH', 'SG', 'MY', 'ID', 'PH', 'VN'],
            fallbackDefault: 'SG'
        },

        // freeText4
        freeText4: {
            type: 'checkbox',
            labelKey: 'acceptTerms',
            required: true,
            htmlId: 'policy',
            errorId: 'policyError',
            defaultValue: false,
            trueValue: 'true',
            falseValue: 'false'
        },

        // freeText5
        freeText5: {
            type: 'hidden',
            value: '-',
            // Auto-fill จาก IP Detection
            autoFillFrom: 'countryCode'
        }
    }
};

// Override CONFIG.language from URL param `lang` or localStorage
(function overrideConfigLanguageFromUrl() {
    try {
        const params = new URLSearchParams(window.location.search);
        let lang = (params.get('lang') || '').toLowerCase();

        // If not in URL, check localStorage
        if (!lang && typeof localStorage !== 'undefined') {
            lang = localStorage.getItem('lang');
        }

        if (lang === 'th' || lang === 'en' || lang === 'id') {
            CONFIG.language = lang;
        }
    } catch (e) {
        // ignore in non-browser environments
    }
})();
